language: php

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  global:
    - IGNORE_PATHS=db/upgrade.php,classes/form/duration.php,classes/form/itemspertime.php
  matrix:
    - MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
    - MOODLE_BRANCH=master DB=mysqli
  
install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit