language: php

sudo: false

addons:
 firefox: "47.0.1"
 postgresql: "9.4"
 apt:
  packages:
   - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  global:
    - IGNORE_PATHS=db/upgrade.php,classes/form/duration.php,classes/form/itemspertime.php
  matrix:
    - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - MOODLE_BRANCH=master DB=pgsql
before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm install 14.6.0
  - nvm use 14.6.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit